feat: scoreCalculator
Imeany12/DupMe pull request #25
Opened 2024-10-13 03:15 UTC by ArcaneSand

## What I did

formular score calculate

## Note

This world is pain

2024-10-15 00:36 UTC, Imeany12 requested changes

2024-10-15 00:36 UTC, Imeany12 commented on apps/server/src/Scoring.ts
> +let correctSequence = ['A', 'A', 'B', 'C', 'D'];
If we are not gonna use this as a default sequence, should we make this an empty arr?

2024-10-15 00:36 UTC, Imeany12 commented on apps/server/src/Scoring.ts
> +}
I think we should add return infer type in this function as well to keep the code consistency

2024-10-15 00:36 UTC, Imeany12 commented on apps/server/src/Scoring.ts
> +}
same as above

2024-10-15 00:36 UTC, Imeany12 commented on apps/server/src/Scoring.ts
> +} {
same as above

2024-10-19 05:40 UTC, ArcaneSand commented
push

2024-10-19 12:28 UTC, Imeany12 approved these changes
LGTM

2024-10-20 05:07 UTC, merged