feat: countdown
Imeany12/DupMe pull request #42
Opened 2024-10-20 18:01 UTC by ArcaneSand

## What I did

Create react component countdown that master suntoh order

## Note

it can be test in /debug

2024-10-21 00:00 UTC, Suntoh commented on apps/client/src/components/CountDown.tsx
> +export default function Countdown() {
Can you make it recieve duration parameters

2024-10-21 01:34 UTC, Imeany12 requested changes

2024-10-21 01:34 UTC, Imeany12 commented on apps/client/src/app/debug/page.tsx
> +      <Countdown />
I don't think we should put the `Countdown` component here

2024-10-21 01:34 UTC, Imeany12 commented on apps/client/src/components/CountDown.tsx
I think the file should be consistent with the component name `Countdown`

2024-10-21 01:34 UTC, Imeany12 commented on apps/client/src/components/CountDown.tsx
> +            clearInterval(timerRef.current!);
```suggestion
            clearInterval(timerRef.current ?? undefined);
```

2024-11-02 09:41 UTC, Suntoh commented
I put the component in the game page and recieve duration as parameters

2024-11-03 03:36 UTC, Imeany12 approved these changes
LGTM 🚀

2024-11-03 05:28 UTC, merged